'use strict';

angular.module('stain')
.config(function($translateProvider) {

	$translateProvider.translations('es', {
   		Spanish : 'Español',
   		English : 'Ingles',
   		Home : 'INICIO',
   		SignOut : 'SALIR',
   		Friends : 'Amigos',
   		Options : 'Opciones',
   		MyProfile : 'Mi Perfil',
   		MyEvents : 'Mis Eventos',
   		MyTours : 'Mis Salidas',
   		AddEvent : 'Agregar Evento',
   		NewTour : 'Nueva Salida',
   		Text1: 'Stain S.A. tiene mas de 100 años de experiencia en la organizacion de eventos. Fundada por Alan Marino en el año 1907. Cuenta con mas de 1000 sucursales en todo el mundo.',
		Text2: 'Stain - Where we go? es una red social creada por la empresa Stain S.A., que brinda la posibilidad a sus usuarios de organizar diferentes tipos de salidas, ya sea solos, en pareja o con amigos. Cuenta con miles de eventos diferentes y es hoy en dia la principal pagina web elegida por usuarios quienes quieren garantizar una salida inolvidable.',
		UpcomingEvents : 'Proximos Eventos',
		Coin : '$',
		NewEvent : 'Nuevo Evento',
		Where : 'Lugar del Evento',
		Price : 'Precio',
		Limit : 'Limite de Personas',
		Description : 'Descripcion',
		Scheduler : 'Horario',
		Morning : 'Mañana',
		Afternoon : 'Tarde',
		Night : 'Noche',
		MORNING2 : 'MORNING',
		AFTERNOON2 : 'AFTERNOON',
		NIGHT2 : 'NIGTH',
		Image : 'Imagen',
		Accept : 'Aceptar',
		Cancel : 'Cancelar',
		Add : 'Agregar Evento',
		Username : 'Nombre de usuario',
		Mail : 'Correo electronico',
		Profile : 'Perfil',
		TypeOfFilm : 'Tipo de Pelicula',
		TypeOfMusic : 'Tipo de Musica',
		TypeOfFood : 'Tipo de Comida',
		LimitAmount : 'Limite de gasto',
		Half : 'Media',
		Orange: 'Naranja',
		Saturday : 'Fiebre',
		NightSaturday : 'De Sabado',
		Fever : 'Por la Noche',
		Gasolera : 'Gasolera',
		With : 'Con',
		SurpriseMe : 'Sorprendeme',
		TypeOfTourSelected : 'Tipo de Tour Seleccionado',
		Date : 'Fecha',
		AvailableEvents : 'Eventos Disponibles',
		Option1 : 'Opcion 1',
		Option2 : 'Opcion 2',
		SelectEvent : 'Seleccionar Evento',
		EventSelected : 'Evento Seleccionado',
		Next : 'Siguiente',
		Back : 'Atras',
		Finish : 'Finalizar',
		TourFinished : 'Salida Finalizada',
		Ubicacion : 'Ubicacion',
		Save : 'Guardar',
		NameEvent : "Nombre del Evento",
		HORROR : 'HORROR',
		ADVENTURE : 'ADVENTURE',
		FANTASY : 'FANTASY',
		COMEDY : 'COMEDY',
		ACTION : 'ACTION',
		ELECTRONIC : 'ELECTRONIC',
		POP : 'POP',
		CLASSIC : 'CLASSIC',
		ROCK : 'ROCK',
		REGGAETON : 'REGGAETON',
		PASTA : 'PASTA',
		FASTFOOD : 'FAST_FOOD',
		PIZZA : 'PIZZA',
		SUSHI : 'SUSHI',
		GRILL : 'GRILL',
		Pleassures : 'Gustos',
		Dates : 'Datos',
		MyFriends : 'Mis Amigos',
		OtherUsers : 'Otros Usuarios',
		DeleteFriend : 'Eliminar Amigo',
		AddFriend : 'Agregar Nuevo Amigo',
		EventDetails : 'Detalle del Evento',
		Attend : 'Asistire',
		Map : 'Mapa',
		Detail : 'Detalle',
		LimitOfPersons : 'Limite de Personas',
		Suggestions: 'Sugerencias',
		NotAttend : 'No Asistire',
		MinPersons : 'Minimo de Personas',
		Find :'Buscar'
	});
});