'use strict';

angular.module('stain')
.config(function($translateProvider) {

	$translateProvider.useSanitizeValueStrategy(null);

	$translateProvider.translations('en', {
   		Spanish : 'Spanish',
   		English : 'English',
   		HOME : 'HOME',
   		SignOut : 'SIGN OUT',
   		Friends : 'Friends',
   		Options : 'Options',
   		MyProfile : 'My Profile',
   		MyEvents : 'My Events',
   		AddEvent : 'Add Event',
   		NewTour : 'New Tour',
   		Text1: 'Stain S.A. has more than 100 years of experience in organizing events. Founded by Alan Marino in 1907. It has more than 1000 branches worldwide.',
   		Text2: 'Stain - Where we go? Is a social network created by the company Stain S.A., which provides the possibility for its users to organize different types of outings, whether alone, as a couple or with friends. It has thousands of different events and is nowadays the main web page chosen by users who want to guarantee an unforgettable outing.',
		UpcomingEvents : 'Upcoming Events',
		Coin : 'U$D',
		NewEvent : 'New Event',
		Where : 'Place for the Event',
		Price : 'Price',
		Limit : 'Limits of Persons',
		Description : 'Description',
		Scheduler : 'Scheduler',
		MORNING2 : 'MORNING',
		AFTERNOON2 : 'AFTERNOON',
		NIGHT2 : 'NIGTH',
		Image : 'Image',
		Morning : 'Morning',
		Afternoon : 'Afternoon',
		Night : 'Night',
		Image : 'Image',
		Accept : 'Accept',
		Cancel : 'Cancel',
		Add : 'Add New Event',
		Username : 'User name',
		Mail : 'Mail',
		Profile : 'Profile',
		TypeOfFilm : 'Type of Film',
		TypeOfMusic : 'Type of Music',
		TypeOfFood : 'Type of Food',
		LimitAmount : 'Limit Amount',
		Half : 'Half',
		Orange: 'Orange',
		Saturday : 'Saturday',
		NightSaturday : 'Night',
		Fever : 'Fever',
		Gasolera : 'Gasolera',
		With : 'With',
		SurpriseMe : 'Surprise Me',
		TypeOfTourSelected : 'Type of Tour Selected',
		Date : 'Date',
		NameEvent : "Name of Event"
	});

	$translateProvider.translations('es', {
   		Spanish : 'Español',
   		English : 'Ingles',
   		Home : 'INICIO',
   		SignOut : 'SALIR',
   		Friends : 'Amigos',
   		Options : 'Opciones',
   		MyProfile : 'Mi Perfil',
   		MyEvents : 'Mis eventos',
   		AddEvent : 'Agregar Evento',
   		NewTour : 'Nueva Salida',
   		Text1: 'Stain S.A. tiene mas de 100 años de experiencia en la organizacion de eventos. Fundada por Alan Marino en el año 1907. Cuenta con mas de 1000 sucursales en todo el mundo.',
		Text2: 'Stain - Where we go? es una red social creada por la empresa Stain S.A., que brinda la posibilidad a sus usuarios de organizar diferentes tipos de salidas, ya sea solos, en pareja o con amigos. Cuenta con miles de eventos diferentes y es hoy en dia la principal pagina web elegida por usuarios quienes quieren garantizar una salida inolvidable.',
		UpcomingEvents : 'Proximos Eventos',
		Coin : '$',
		NewEvent : 'Nuevo Evento',
		Where : 'Lugar del Evento',
		Price : 'Precio',
		Limit : 'Limite de Personas',
		Description : 'Descripcion',
		Scheduler : 'Horario',
		Morning : 'Mañana',
		Afternoon : 'Tarde',
		Night : 'Noche',
		MORNING2 : 'MORNING',
		AFTERNOON2 : 'AFTERNOON',
		NIGHT2 : 'NIGTH',
		Image : 'Imagen',
		Accept : 'Aceptar',
		Cancel : 'Cancelar',
		Add : 'Agregar Evento',
		Username : 'Nombre de usuario',
		Mail : 'Correo electronico',
		Profile : 'Perfil',
		TypeOfFilm : 'Tipo de Pelicula',
		TypeOfMusic : 'Tipo de Musica',
		TypeOfFood : 'Tipo de Comida',
		LimitAmount : 'Limite de gasto',
		Half : 'Media',
		Orange: 'Naranja',
		Saturday : 'Fiebre',
		NightSaturday : 'De Sabado',
		Fever : 'Por la Noche',
		Gasolera : 'Gasolera',
		With : 'Con',
		SurpriseMe : 'Sorprendeme',
		TypeOfTourSelected : 'Tipo de Tour Seleccionado',
		Date : 'Fecha',
		NameEvent : "Nombre del Evento"
	});

	var language = (navigator.language || navigator.browserLanguage).split('-')[0];
    $translateProvider.preferredLanguage(language);
});